---
title: "Webinar 2 - Dashboards em R"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme:
      version: 4
      primary: "#f15bb5"
      navbar-bg: "#9b5de5"
      base_font: 
        google: Open Sans
      code_font:
        google: JetBrains Mono
runtime: shiny
---


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(readxl)
library(shiny)
library(bslib)
library(highcharter)

#remotes::install_github("rstudio/bslib")

titanic <- read.csv("train.csv")
netflix <- read_xlsx("netflix_series_limpo.xlsx")
imdb_series <- read_xlsx("imdb_series.xlsx")

minhascores <- c("#9b5de5","#f15bb5","#fee440","#00bbf9","#00f5d4")


theme_set(theme_minimal())

```

Page 1 {data-orientation=rows}
=====

Column{data-width=200 .sidebar}
--------------------------------------------------------------

```{r shiny1}
sliderInput("idade_crianca", 
            label = "Idade máxima para ser considerada criança:",
            min = 1, 
            max = 16, 
            value = 10, 
            step = 1,
            dragRange = TRUE)

selectInput("n_bins", 
            label = "Número de categorias para o Histograma",
            choices = c(10,20,30,40), selected = 30)

selectInput("genero",
            label = "Escolha o Gênero",
            choices = c("Masculino"="male","Feminino"="female",
                        "Todos"="all"), selected = "Masculino")

sliderInput("idade",
            label = "Escolha a idade máxima (de 0 a...",
            min = 1, max = 80, value = 80, step = 1, 
            dragRange = TRUE)

```


Row {data-heigth=500}
--------------------------------------------------------------

### Total de passageiros

```{r}

passenger <- titanic %>% 
  nrow()

renderValueBox({

valueBox(prettyNum(passenger, big.mark = ','), 
         icon = 'fa-ship', caption = "Passageiros",
         color="#9b5de5")
}
)
```

### Total de sobrevivientes

```{r fig.width=12, fig.height=6}

total_survived <- titanic %>% 
  summarize(survived = sum(Survived))
  

renderValueBox({

valueBox(prettyNum(total_survived, big.mark = ','), 
         icon = 'fa-thumbs-up', caption = "Sobrevivientes",
         color="#f15bb5")
}
)

```


### Total de mulheres

```{r}

women <- titanic %>%
  filter(Sex == "female") %>% 
  nrow()

renderValueBox({

valueBox(prettyNum(women, big.mark = ','), 
         icon = 'fa-women', 
         caption = "Mulheres",
         color="#fee440")
}
)
```

### Total de crianças

```{r}

child <- titanic %>%
  filter(Age < 10) %>% 
  nrow()

renderValueBox({

valueBox(prettyNum(titanic %>%
                     filter(Age < input$idade_crianca) %>% 
                     nrow(), big.mark = ','), 
         icon = 'fa-baby', 
         caption = "Crianças",
         color="#00bbf9")
}
)
```

Row {data-heigth=500 .tabset .tabset-fade}
--------------------------------------------------------------

### Distribuição dos passageiros por idade, sexo e sobrevivência

```{r}

titanic$Survived <- factor(titanic$Survived, levels = c(0,1),
                           labels=c("Óbitos","Sobrevivientes"))

renderPlotly({
 if ("all" %in% input$genero){
    b1 <- titanic %>%
      filter(Sex %in% c("male","female")) %>% 
      filter(Age < input$idade) %>% 
    ggplot(aes(Survived, Age, fill = Survived))+
    geom_boxplot()+
    scale_fill_manual(values=minhascores)+
    theme(axis.title.x = element_blank(),
          legend.position = "none")
  ggplotly(b1)}
  else{
    b1 <- titanic %>%
    filter(Sex==input$genero) %>% 
      filter(Age < input$idade) %>%
    ggplot(aes(Survived, Age, fill=Survived))+
    geom_boxplot()+
    scale_fill_manual(values=minhascores)+
    theme(axis.title.x = element_blank(),
          legend.position = "none")
  ggplotly(b1)}
})
```

### Distribuição por densidade

```{r}


renderPlotly({
  if ("all" %in% input$genero){
  b2 <- titanic %>% 
    filter(Sex %in% c("male","female")) %>% 
    filter(Age < input$idade) %>%
    ggplot(aes(Age, fill=Survived))+
    geom_density(alpha=0.4)+
    scale_fill_manual(values=minhascores)
  ggplotly(b2)
  } else {
     b2 <- titanic %>% 
    filter(Sex==input$genero) %>% 
       filter(Age < input$idade) %>%
    ggplot(aes(Age, fill=Survived))+
    geom_density(alpha=0.4)+
    scale_fill_manual(values=minhascores)
  ggplotly(b2)
    
  }
})
```

### Histograma

```{r}
renderPlotly({
  if ("all" %in% input$genero){
   b3 <- titanic %>% 
    filter(Sex %in% c("male","female")) %>% 
     filter(Age < input$idade) %>%
    ggplot(aes(Age, fill=Survived))+
    geom_histogram(alpha=0.9, bins = input$n_bins)+
    scale_fill_manual(values=minhascores)
  ggplotly(b3)
  } else {
    b3 <- titanic %>% 
      filter(Sex == input$genero) %>% 
      filter(Age < input$idade) %>%
    ggplot(aes(Age, fill=Survived))+
    geom_histogram(alpha=0.9, bins = input$n_bins)+
    scale_fill_manual(values=minhascores)
  ggplotly(b3)
  }
})
```


Page 2
====

Column{data-width=200 .sidebar}
--------------------------------------------------------------
```{r shiny2}
sliderInput("numero_seriados", 
            label = "Escolha o número de seriados:",
            min = 1, 
            max = 30, 
            value = 20, 
            step = 1,
            dragRange = TRUE)


```

Column {data-width=400}
-------------------------------------------------------------------

### Seriados mais assistidos

```{r}
renderHighchart({
netflix %>% 
  group_by(series_title) %>% 
  count() %>% 
  arrange(desc(n)) %>% 
  ungroup() %>% 
  top_n(input$numero_seriados, wt=n)%>% 
  hchart(type = "bar", hcaes(series_title, n), color="#9b5de5") %>%
  hc_add_theme(hc_theme_elementary())
})
```


Column {data-width=400}
-----------------------------------------------------------------------

### Nota IMDb vs Número de capítulos assistidos

```{r}
imdb_series_nota_media <- imdb_series %>% 
  group_by(series_name) %>% 
  summarize(nota=mean(UserRating))

nomes <- data.frame(pt=c("Grimm: Contos de Terror", "Era Uma Vez",
                         "Como Defender um Assassino", 
                         "La Casa de Papel",
                         "Lúcifer","Motel Bates",
                         "Pânico: A Série de TV"),
                    en=c("Grimm","Once Upon a Time",
                         "How to Get Away With Murder",
                         "Money Heist",
                         "Lucifer","Bates Motel","Scream"))

netflix_imdb_pt_en <- netflix %>%
  group_by(series_title) %>% 
  count() %>% 
  arrange(desc(n)) %>% 
  ungroup() %>% 
  left_join(nomes, by=c("series_title"="en")) %>% 
  mutate(titulo_pt=ifelse(is.na(pt), series_title, pt)) %>% 
  left_join(imdb_series_nota_media, by=c("titulo_pt"="series_name")) %>% 
  select(-pt)

renderHighchart({
netflix_imdb_pt_en %>% 
  top_n(input$numero_seriados, wt=n) %>% 
    hchart(hcaes(n, round(nota, 2)), color="#f15bb5", 
         type = "scatter") %>% 
    hc_xAxis(title = list(text = "Capítulos assistidos")) %>%
    hc_yAxis(title=list(text = "Nota IMDB")) %>% 
    hc_add_theme(hc_theme_elementary())
})
```

### Seriados com mais capítulos por assistir

```{r}
assistidos_vs_total <- netflix_imdb_pt_en %>% 
  left_join(imdb_series, by=c("titulo_pt"="series_name")) %>% 
  group_by(series_title) %>% 
  summarize(total=n()) %>% 
  left_join(netflix_imdb_pt_en, by="series_title") %>% 
  mutate(faltam=total-n) %>% 
  filter(faltam >=0)

library(knitr)

assistidos_vs_total %>% 
  select(1,6) %>% 
  arrange(desc(faltam)) %>% 
  filter(faltam > 5) %>% 
  kable(digits = 2)
```

